services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: on-failure:5
    network_mode: host
    volumes:
      - /srv/docker/hobby/nginx/html:/usr/share/nginx/html
      - /srv/docker/hobby/nginx/configs:/etc/nginx/templates
      - /etc/letsencrypt:/etc/letsencrypt:ro
