services:
  wg-easy-hobby:
    image: ghcr.io/wg-easy/wg-easy:latest
    container_name: wg-easy-hobby
    restart: on-failure:5
    environment:
      - WG_HOST=${WG_HOST}
      - PASSWORD_HASH=${WG_PASSWORD_HASH}
      - WG_PORT=51822
      - PORT=51823
      - WG_DEFAULT_ADDRESS=${WG_DEFAULT_ADDRESS}
      - WG_DEFAULT_DNS=${WG_DEFAULT_DNS}
      - WG_ALLOWED_IPS=20.20.0.0/24
    volumes:
      - /srv/docker/hobby/wg-easy/data:/etc/wireguard
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
