services:
  minecraft:
    image: itzg/minecraft-server:latest
    container_name: minecraft
    restart: on-failure:5
    network_mode: host
    environment:
      EULA: "TRUE"
      TYPE: PAPER
      VERSION: ${MC_VERSION}
      ONLINE_MODE: "FALSE"
      MOTD: ${MOTD}
      INIT_MEMORY: ${INIT_MEMORY}
      MAX_MEMORY: ${MAX_MEMORY}
      JVM_XX_OPTS: ${JVM_XX_OPTS}
      RCON_ENABLED: ${RCON_ENABLED}
      RCON_PORT: ${RCON_PORT}
      RCON_PASSWORD: ${RCON_PASSWORD}
      PLUGINS: ${PLUGINS}
      UID: "1000"
      GID: "1000"
    volumes:
      - /srv/docker/hobby/minecraft/data:/data
      - /srv/docker/hobby/minecraft/data/plugins/AuthMe/config.yml:/data/plugins/AuthMe/config.yml

  mysql:
    image: mysql:8
    container_name: mysql
    restart: on-failure:5
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - /srv/docker/hobby/mysql/data/data:/var/lib/mysql
    networks:
      - server-net

networks:
  server-net:
    external: true
