services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:latest
    container_name: wg-easy
    restart: unless-stopped
    environment:
      - WG_HOST=${WG_HOST}
      - PASSWORD_HASH=${WG_PASSWORD_HASH}
      - WG_PORT=51820
      - PORT=51821
      - WG_DEFAULT_ADDRESS=${WG_DEFAULT_ADDRESS}
      - WG_DEFAULT_DNS=${WG_DEFAULT_DNS}
      - WG_PERSISTENT_KEEPALIVE=25
      - WG_ALLOWED_IPS=10.10.0.0/24
    volumes:
      - /srv/docker/server-management/wg-easy/data:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "127.0.0.1:51821:51821/tcp"
    networks:
      - server-net
    cap_add:
      - NET_ADMIN
      - SYS_MODULE

networks:
  server-net:
    external: true
