services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:latest
    container_name: wg-easy
    restart: unless-stopped
    environment:
      - WG_HOST=${WG_HOST}
      - PASSWORD_HASH=${WG_PASSWORD_HASH}
      - WG_PORT=51820
      - WG_DEFAULT_ADDRESS=${WG_DEFAULT_ADDRESS}
      - WG_DEFAULT_DNS=${WG_DEFAULT_DNS}
    volumes:
      - /srv/docker/server-management/wg-easy/data:/etc/wireguard
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
