services:
  oci-server-management-portainer:
    image: portainer/portainer-ee:latest
    container_name: oci-server-management-portainer
    restart: unless-stopped
    command: --tlscert /certs/live/${DOMAIN}/fullchain.pem --tlskey /certs/live/${DOMAIN}/privkey.pem
    ports:
      - "127.0.0.1:9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/docker/server-management/oci-server-management-portainer/data:/data
      - /etc/letsencrypt:/certs:ro
    networks:
      - server-net

networks:
  server-net:
    name: server-net
    driver: bridge
    ipam:
      config:
        - subnet: ${SERVER_NET_CIDR}
